services:
    client:
        build:
            context: ./client
        ports:
            - "3000:80"
        depends_on:
            server:
                condition: service_healthy

    server:
        build:
            context: ./server
        ports:
            - "5000:5000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
            interval: 30s
            retries: 3
            start_period: 10s
            timeout: 10s
